
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd5\xb4e\x00\xf9L\x93>\xa1\x1cz\x99\xfe\x13}g'
    
_lr_action_items = {'PLAINTEXT':([0,1,2,3,4,5,8,10,13,14,15,17,18,19,20,24,],[4,4,10,4,-13,4,4,-12,17,4,10,-12,-5,4,10,-6,]),'DOL_LBRACE':([0,1,2,3,4,10,18,24,],[8,8,8,8,-13,-12,-5,-6,]),'PERC_LBRACE':([0,1,2,3,4,8,10,14,15,18,19,20,24,],[5,5,5,5,-13,5,-12,5,5,-5,5,5,-6,]),'RBRACE':([4,10,13,14,15,16,17,18,19,20,21,22,23,25,26,],[-13,-12,18,-14,-14,24,-12,-5,-14,-14,-8,-11,-7,-10,-9,]),'$end':([0,1,2,3,4,6,7,9,10,11,12,18,24,],[-14,-14,-14,-14,-13,0,-4,-3,-12,-1,-2,-5,-6,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pholder_tag':([0,1,2,3,8,14,15,19,20,],[1,1,1,1,14,19,19,19,19,]),'plaintext':([0,1,2,3,5,8,14,15,19,20,],[2,2,2,2,13,15,20,20,20,20,]),'inner_tag':([0,1,2,3,],[3,3,3,3,]),'inner_tag_cont':([14,15,19,20,],[21,23,25,26,]),'inner_tag_name':([8,],[16,]),'expression':([0,1,2,3,],[6,9,11,12,]),'empty':([0,1,2,3,14,15,19,20,],[7,7,7,7,22,22,22,22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> plaintext expression','expression',2,'p_expression','pyslate2/parser.py',52),
  ('expression -> inner_tag expression','expression',2,'p_expression','pyslate2/parser.py',53),
  ('expression -> pholder_tag expression','expression',2,'p_expression','pyslate2/parser.py',54),
  ('expression -> empty','expression',1,'p_expression','pyslate2/parser.py',55),
  ('pholder_tag -> PERC_LBRACE plaintext RBRACE','pholder_tag',3,'p_pholder_tag','pyslate2/parser.py',59),
  ('inner_tag -> DOL_LBRACE inner_tag_name RBRACE','inner_tag',3,'p_inner_tag','pyslate2/parser.py',63),
  ('inner_tag_name -> plaintext inner_tag_cont','inner_tag_name',2,'p_inner_tag_name','pyslate2/parser.py',67),
  ('inner_tag_name -> pholder_tag inner_tag_cont','inner_tag_name',2,'p_inner_tag_name','pyslate2/parser.py',68),
  ('inner_tag_cont -> plaintext inner_tag_cont','inner_tag_cont',2,'p_inner_tag_cont','pyslate2/parser.py',72),
  ('inner_tag_cont -> pholder_tag inner_tag_cont','inner_tag_cont',2,'p_inner_tag_cont','pyslate2/parser.py',73),
  ('inner_tag_cont -> empty','inner_tag_cont',1,'p_inner_tag_cont','pyslate2/parser.py',74),
  ('plaintext -> plaintext PLAINTEXT','plaintext',2,'p_plaintext','pyslate2/parser.py',78),
  ('plaintext -> PLAINTEXT','plaintext',1,'p_plaintext','pyslate2/parser.py',79),
  ('empty -> <empty>','empty',0,'p_empty','pyslate2/parser.py',83),
]
