
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x84I\x01\x9b)\xa1\xba,hKa\xab\xef\xf1\x9c\x87'
    
_lr_action_items = {'RBRACE':([3,10,11,12,13,16,18,19,21,22,23,24,25,26,27,28,],[-14,-13,17,-15,-15,24,-8,-12,-15,-15,-9,-5,29,-15,-10,-11,]),'PLAINTEXT':([0,2,3,5,6,7,8,10,12,13,17,20,21,22,24,26,29,],[3,3,3,3,3,3,3,-13,3,3,-6,3,3,3,-5,3,-7,]),'$end':([0,1,2,3,4,6,7,9,10,14,15,17,24,29,],[-15,0,-15,-14,-4,-15,-15,-2,-13,-1,-3,-6,-5,-7,]),'PERC_LBRACE':([0,2,3,5,6,7,10,12,13,17,20,21,22,24,26,29,],[8,8,-14,8,8,8,-13,8,8,-6,8,8,8,-5,8,-7,]),'COLON':([3,10,12,],[-14,-13,20,]),'DOL_LBRACE':([0,2,3,6,7,10,17,24,29,],[5,5,-14,5,5,-13,-6,-5,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,6,7,],[1,9,14,15,]),'inner_tag':([0,2,6,7,],[2,2,2,2,]),'inner_tag_cont':([12,13,21,22,26,],[18,23,27,28,18,]),'empty':([0,2,6,7,12,13,21,22,26,],[4,4,4,4,19,19,19,19,19,]),'inner_tag_name':([5,20,],[11,25,]),'plaintext':([0,2,3,5,6,7,8,12,13,20,21,22,26,],[6,6,10,12,6,6,16,21,21,26,21,21,21,]),'pholder_tag':([0,2,5,6,7,12,13,20,21,22,26,],[7,7,13,7,7,22,22,13,22,22,22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> plaintext expression','expression',2,'p_expression','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',73),
  ('expression -> inner_tag expression','expression',2,'p_expression','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',74),
  ('expression -> pholder_tag expression','expression',2,'p_expression','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',75),
  ('expression -> empty','expression',1,'p_expression','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',76),
  ('pholder_tag -> PERC_LBRACE plaintext RBRACE','pholder_tag',3,'p_pholder_tag','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',84),
  ('inner_tag -> DOL_LBRACE inner_tag_name RBRACE','inner_tag',3,'p_inner_tag','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',88),
  ('inner_tag -> DOL_LBRACE plaintext COLON inner_tag_name RBRACE','inner_tag',5,'p_inner_tag','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',89),
  ('inner_tag_name -> plaintext inner_tag_cont','inner_tag_name',2,'p_inner_tag_name','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',96),
  ('inner_tag_name -> pholder_tag inner_tag_cont','inner_tag_name',2,'p_inner_tag_name','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',97),
  ('inner_tag_cont -> plaintext inner_tag_cont','inner_tag_cont',2,'p_inner_tag_cont','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',101),
  ('inner_tag_cont -> pholder_tag inner_tag_cont','inner_tag_cont',2,'p_inner_tag_cont','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',102),
  ('inner_tag_cont -> empty','inner_tag_cont',1,'p_inner_tag_cont','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',103),
  ('plaintext -> PLAINTEXT plaintext','plaintext',2,'p_plaintext','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',109),
  ('plaintext -> PLAINTEXT','plaintext',1,'p_plaintext','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',110),
  ('empty -> <empty>','empty',0,'p_empty','/home/alek/PycharmProjects/pyslate/pyslate2/parser.py',118),
]
